FROM node:20

WORKDIR /server

RUN corepack enable && corepack prepare yarn@3.2.1 --activate

COPY package.json yarn.lock .yarnrc.yml ./
COPY apps/backend/package.json ./apps/backend/package.json

RUN yarn install

COPY . .

WORKDIR /server/apps/backend

RUN yarn build

WORKDIR /server/apps/backend/.medusa/server

RUN touch yarn.lock
RUN yarn install

ENV NODE_ENV=production

EXPOSE 9000

CMD ["yarn", "start"]