FROM node:20

WORKDIR /app

RUN corepack enable

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn ./.yarn

COPY apps/backend/package.json ./apps/backend/package.json

RUN yarn install --immutable

COPY . .

WORKDIR /app/apps/backend

RUN yarn build

EXPOSE 9000

CMD ["yarn", "start"]